This is a recent commit for the new articles
apitoolkit/apitoolkit-landing pull request #6
Opened 2022-09-24 17:15 UTC by jessyrosy

2022-10-04 11:03 UTC, tonyalaribe commented
Thanks for the pullrequest. I noticed some things though:
1. You're naming article urls in all caps Eg 
<img width="466" alt="image" src="https://user-images.githubusercontent.com/6564482/193801313-b460486d-5e9e-4a75-ab45-272035aa4b35.png">
   Could you change them to small letters. all caps is basically shouting.
2.  You have file names such as `content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/Screenshot (52).png` and `content/Dashboard before-integration.png` could you rename scrennshot (52) to something that actually describes what the image is.  And could you add a hyphen between Dashboard and before
3.  You added a lot of images to the repository which are not used anywhere in the articles. Could you go through all the images again and delete the ones that are not used in the articles. Examples that I found are content/API-keys-generation.png, content/Endpoint.png, content/endpoint_list.png, etc. There's a lot of them, please find them and remove them. 
4. You have a lot of images coming from stock image sites, and you don't add any content attributions. This is a legal risk for us as a business, and we could easily be sued by any of them. Please add content attributions to any images you use. Let me know if you dont know how. 
5.

2022-10-04 11:10 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +date: 2022-05-24T08:05:56+02:00
Why are you using a date in may? This would hurt our SEO efforts if you're backdating articles

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/6564482/193804243-fdd14dca-9f65-467c-8a05-8e989d4be957.png">

2022-10-04 11:18 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +- Speed: A detailed and easy-to-use API documentation speeds up the integration of your API by making it more accessible to new users and even returning users.
How is this different from `Reduced Onboarding Time`?

2022-10-04 11:19 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +These pieces of documentation are so effective for the following reasons:
```suggestion
Good documentation is effective for the following reasons: 
```

2022-10-04 11:22 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +There are various API documentation tool that are widely available. Here is our selection of the essentials
```suggestion
There are various widely available API documentation tools. These are a few:
```

2022-10-04 12:07 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +- Postman
```suggestion
### Postman
```

2022-10-04 12:20 UTC, tonyalaribe requested changes

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +![postman](./draft%20-%20API%20Documentation%20Tool.png)
A picture showing postman documentation tool is better than a picture of their landing page.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +- Dropbox API Reference
```suggestion
### Dropbox API Reference
```

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +This dropbox API Reference ia an outstanding example of top-notch reference material. In contrast to the other competitors on this list, Dropbox asks you to select your preferred programming language
The title of the article is `Basic API Documentation Tools`. 
How is dropbox an API documentation tool? What you're describing basically says Dropbox is a good example of an API documentation, not that it's an API documentation tool.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +![Swaggerhub](./Screenshot%20(52).png)
Please change this screenshot file name to something more representative.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +This is ideal for teams and enterprises, SwaggerHub is an online API documentation tool designed to simplify and accelerate API documentation. Using the API editor, you can more easily achieve compli
You're saying a lot, but not saying anything at the same time. As a reader, I don't still understand what SwaggerHub is and when i'm supposed to use it or how i'm supposed to use it.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +The REST API documentation for GitHub is also highly lauded by developers. Github's documentation doesn't attempt to cram too much information onto a single page, similar to Dropbox. The straightforw
The title of the article is `Basic API Documentation Tools`.
How is github an API documentation tool? You're describing an example of good documentation, not a tool.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +- ReadMe
```suggestion
### ReadMe
```

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +-APIDOC
I don't understand what this is from your explanation. Is it a tool? Is it a desktop app? is it an example? WHen and why would I use it?

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +## Basis of a good documentation
Please add links from all the examples to their websites.

2022-10-04 12:20 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +Any of the above tools  can assist you in producing interactive, user-friendly, and simple to maintain online API documentation. When assessing tools, be sure to consider both your must-haves and nic
Why is apitoolkit not listed here, when it's a tool for api documentation?

2022-10-04 12:21 UTC, tonyalaribe commented on content/blog/API-SPECS-VS-DOCUMENTATION-AN-WHAT-IT-MEANS-FOR-YOU/_index.md
> +date: 2022-05-24T08:05:56+02:00
Why is this date in the future?

2022-10-04 12:22 UTC, tonyalaribe commented on content/blog/API-SPECS-VS-DOCUMENTATION-AN-WHAT-IT-MEANS-FOR-YOU/_index.md
> +title: "API DOCUMENTATION VS API SPECIFICATION - WHAT IT MEANS FOR YOU"
Please don't use all caps for blog titles or URLs it's basically shouting

2022-10-04 12:33 UTC, tonyalaribe commented on content/blog/API-SPECS-VS-DOCUMENTATION-AN-WHAT-IT-MEANS-FOR-YOU/_index.md
> +API's documentation serves as a user guide or manual, explaining how to utilize the API to its users. Developers are the primary audience for API documentation this doesnt mean that non-techies cant
You already defined API documentation in the other blog post. Let's not spend so many paragraphs re defining API Documentation in every blog post.  It's better to give a one line explanation and then link to another article that explained the concept.  Can you do that here.

2022-10-04 12:33 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +API modeling enables us to set up better communication procedures, before going ahead to design our API.  We must be very careful when choosing names for our resources because APIs are permanent. Add
Are they really permanent?

2022-10-04 12:35 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +API modeling enables us to set up better communication procedures, before going ahead to design our API.  We must be very careful when choosing names for our resources because APIs are permanent. Add
This paragraph doesn't define what API modelling is, so i'm not sure what it is even after reading this.

2022-10-04 12:41 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +---
Please change the folder name of this article from all caps to small caps or title case

2022-10-04 12:44 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +![API-modeling](./istockphoto-1336160494-170667a.jpg)
Add content attribution

2022-10-04 12:45 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +More than your expensive databases or the fine method your code was designed, your end customers are interested in the outcomes that your API makes attainable. Your users need answers to question, al
```suggestion
More than your expensive databases or the fine method your code was designed, your end customers are interested in the outcomes that your API makes attainable. Your users need answers to questions. Always remember that they want a problem solved. If your model can't solve the problem then it is an issue.
```

2022-10-04 12:57 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +## The Process Involved in API Modeling
Please don't plagiarize peoples articles. You put us at risk of legal action from any of these companies. 
https://tyk.io/blog/before-you-design-your-api-model-your-api/

2022-10-04 12:58 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +## The Goal of API Modeling
Can you include charts that show an example of such an API model?

2022-10-04 12:58 UTC, tonyalaribe commented on content/blog/API-MODELING-THE-PROCESS-AND-GOAL-/index.md
> +## The Process Involved in API Modeling
If you're getting ideas from any article or website, please add a references section at the bottom of your article and link to those articles there.

2022-10-04 18:10 UTC, tonyalaribe commented on content/blog/RESOURSE-MODELLING/index.md
> +---
Please also rename the folder name. 
1. You have a typo,`content/blog/RESOURSE-MODELLING/index.md`  RESOURCE not resourse. 
2. It should not be all caps.

2022-10-04 19:00 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +Encourage potential customers to check what they read in the API documentation using the API console right away. A console makes getting started quick and easy, with no risk to the consumer. Experime
```suggestion
If possible, you should also offer an interactive console to interact with your APIs. An interactive console makes getting started quick and easy, with no risk to the consumer. Encourage potential customers to test what they read in the API documentation using the API console. Experimentation is powerful. The work required to build a console or sandbox environment for users to interact with your API is rather high, but it can greatly aid engineers in understanding the value of your API graphically. Many organizations, including Microsoft and GitHub, provide interactive consoles for experimenting with their API services.
```
Show screenshots

2022-10-04 19:01 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +## Mistakes to AVOID
I think you should break this Mistakes to Avoid out into a separate article.

2022-10-04 19:02 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +- Avoid Using Jargon
```suggestion
### Avoid Using too much Jargon
```

2022-10-04 19:03 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +- Using too many Endpoints
We can't tell anyone how many endpoints to have. Also, this article is about API documentation, not how they should build the APIs

2022-10-04 19:04 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +- Focusing on Competitors
```suggestion
### Focusing on Competitors
```

2022-10-04 19:04 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +If its not organized then its a problem, every developer wants to have easy access to what they want in order to solve their problem as fast as they can.
Elaborate more on this with examples.

2022-10-04 19:05 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +- Improper Structuring
```suggestion
### Bad Documentation Structure
```

2022-10-04 19:05 UTC, tonyalaribe commented on content/blog/WRITING-API-DOCUMENTATION-BEST-PRACTICES-AND-MISTAKES-TO-AVOID/_index.md
> +Finally, a good API documentation is worthwhile even when it takes work. It is a potent tool for accelerating the development and maturity of your APIs. It lays the groundwork for an excellent develo
Find a way to integrate apitoolkit into your articles.

2022-10-05 15:41 UTC, jessyrosy commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +date: 2022-05-24T08:05:56+02:00
The last time we spoke about the dates, you said I shouldn't alter the dates. But it will be resolved

2022-10-05 18:08 UTC, tonyalaribe commented on content/blog/API-DOCUMENTATION-TOP-TOOLS-AND-USING-THEM-RIGHT/index.md
> +API documentation is a technical content that is both a machine and human readable file that explains the how-tos of an API and what a particular API can perform. It is a precise reference source tha
You're conflating "API", and "API docs" 
Apis are for machines, and maybe humans. API docs are for the humans who want to use the API

2022-10-10 18:04 UTC, tonyalaribe commented on content/blog/api-trends/index.md
>  ![API Trends](./image1.jpg)
This image doesn't exist

2022-10-10 18:10 UTC, tonyalaribe commented on content/blog/resourse-modeling-in-rest-api-design/index.md
> +## Guidlines to Designing Your Resource-Model
```suggestion
## Guidelines to Designing Your Resource-Model
```

2022-10-10 18:25 UTC, tonyalaribe commented on content/blog/resourse-modeling-in-rest-api-design/index.md
> +![resource-modeling](../resource.jpg)
Broken urlpath.  Should be 
```suggestion
![resource-modeling](./resource.jpg)
```

2022-10-10 18:26 UTC, tonyalaribe commented on content/blog/resourse-modeling-in-rest-api-design/index.md
> +In Rest API any information that can be named can be a resource. Resources in Rest can either be a sigleton or a collection. Resource modeling is a concept for resource management that lets you see r
Add one or two empty lines before this paragraph. It looks broken if you view this page.

2022-10-10 18:28 UTC, tonyalaribe commented on content/docs/Quickstarts/Golang.md
> +1. Deploy your application or send test http requests to your service
```suggestion
4. Deploy your application or send test http requests to your service
```

2022-10-10 18:28 UTC, tonyalaribe commented on content/docs/Quickstarts/Golang.md
> +2. Check API log explorer or Endpoints pages on the APIToolkit dashboard to see if your test request was processed correctly
```suggestion
5. Check the API log explorer or Endpoints pages on the APIToolkit dashboard to see if your test request was processed correctly 
```

2022-10-11 14:48 UTC, tonyalaribe commented on content/blog/resource/index.md
> +![Resource-modeling](./api-modeling.jpg)
Could you add an image description or attribution here.

2022-10-11 14:51 UTC, tonyalaribe commented on content/docs/Dashboard/generating-api-keys.md
>  How to Generate API keys in APIToolkit
Can you make this a heading? ###

2022-10-11 14:55 UTC, tonyalaribe commented on content/docs/Dashboard/generating-api-keys.md
> +Sign up / Sign in to the [API dashboard](https://app.apitoolkit.io). This is the first step to getting started.
Can you change these back to bullet points?

2022-10-11 14:55 UTC, tonyalaribe commented on content/docs/Dashboard/generating-api-keys.md
> +![API title](../api-title.png)
The images are broken.
![image](https://user-images.githubusercontent.com/6564482/195126012-8c7e5a13-1299-483e-9a7c-1a19cb20274f.png)

2022-10-11 14:57 UTC, tonyalaribe commented on content/docs/Dashboard/creating-a-project.md
> +![Welcome on board](./welcome-on-board.png)
These changes are breaking the images. Could you change it back

![image](https://user-images.githubusercontent.com/6564482/195126273-62b8fc0e-e7b3-492b-a46a-a31be1cc39d0.png)

2022-10-12 08:45 UTC, jessyrosy commented on content/docs/Dashboard/generating-api-keys.md
> +![API title](../api-title.png)
It's different on my end though.

2022-10-12 20:52 UTC, tonyalaribe approved these changes

2022-10-12 20:53 UTC, merged